"""Edit Campground Model

Revision ID: 583bcd3ebd39
Revises: d445d1f7b3bc
Create Date: 2020-09-30 08:11:53.510020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583bcd3ebd39'
down_revision = 'd445d1f7b3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campground', sa.Column('city', sa.String(), nullable=False))
    op.add_column('Campground', sa.Column('country', sa.String(), nullable=False))
    op.add_column('Campground', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('Campground', sa.Column('province', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
