const cities = [
    'Burns Lake',
    'North Vancouver',
    'Oliver',
    'Golden',
    'Ladysmith',
    'Powell River',
    'Hazelton',
    'Spences Bridge',
    'Quesnel',
    'Port McNeill',
    'Abbotsford',
    'Clearwater',
    'Anahim Lake',
    'Anmore',
    'Kelowna',
    'Armstrong',
    'Bridesville',
    'Port Alberni',
    'Ashcroft',
    'Hagensborg',
    'Kaleden',
    'Chilanko Forks',
    'Courtenay',
    'Sechelt',
    "Hudson's Hope",
    'Lake Country',
    'Lake Cowichan',
    'Fruitvale',
    'McBride',
    'Prince George',
    'Tofino',
    'Francois Lake',
    'Christina Lake',
    'Blue River',
    'Hornby Island',
    'Nanaimo',
    'Cache Creek',
    'Osoyoos',
    'Campbell River',
    'Burnaby',
    'Burton',
    'Penticton',
    'Rosedale',
    'Donald',
    'Canim Lake',
    'Valemount',
    'Hixon',
    'Revelstoke',
    'Radium Hot Springs',
    'Lone Butte',
    'Kitwanga',
    'Castlegar',
    'Vernon',
    'Malahat',
    'New Denver',
    'Agassiz',
    'Squamish',
    'Chemainus',
    'Cultus Lake',
    'Trail',
    'Merritt',
    'Nelson',
    'Coombs',
    'Hope',
    'Bridge Lake',
    'Lee Creek',
    'Chilliwack',
    'Cranbrook',
    'Malakwa',
    'Horsefly',
    'Bowser',
    'Gabriola Island',
    'Surrey',
    'Horsefly Lake',
    'Aldergrove',
    'Lumby',
    'Elkford',
    'Loon Lake',
    'Fair Harbour',
    'Fairmont Hot Springs',
    'Fawn Lake', 'Fernie',
    'Vanderhoof',
    'Blind Bay',
    'Fort Steele',
    'Telkwa',
    'Victoria',
    'Lillooet',
    'Hedley',
    'Cherryville',
    'Dawson City',
    'Grand Forks',
    'Greenwood',
    'Sidney',
    'Pender Island',
    'Harrison Hot Springs',
    'Quadra Island',
    'Salmon Arm',
    'Heffley Lake',
    'Qualicum Beach',
    'Ucluelet',
    'Rock Creek',
    'Sicamous',
    'Kamloops',
    'Winlaw',
    'Kaslo',
    'Eagle Creek',
    'Nakusp',
    'Harrison Mills',
    'Kimberley',
    'Mara',
    'Port Edward',
    'Knutsford',
    'Lac La Hache',
    'Crawford Bay',
    'Slocan',
    'Fanny Bay',
    'Logan Lake',
    'Sheridan Lake',
    'Enderby',
    'Magna Bay',
    'Manning Park',
    'Dawson Creek',
    'Mirror Lake',
    'Monte Lake',
    'Hathaway Lake',
    'Erickson',
    'Iskut',
    'Sparwood',
    'Nanoose Bay',
    'Tahsis',
    'Muncho Lake',
    'Saanichton',
    'Westbridge',
    'Bamfield',
    'Black Creek',
    'Creston',
    'Parksville',
    'Taylor',
    'Garden Bay',
    'McLure',
    'Fort Fraser',
    'Fort St. James',
    'Quesnel Lake',
    'Port Hardy',
    'Prince Rupert',
    'Princeton',
    'Qualicum Bay',
    'Parson',
    'Kitimat',
    'Keremeos',
    'Little Fort',
    'Duncan',
    'Smithers',
    'Whistler',
    'Salmo',
    'Charlie Lake',
    'Rossland',
    'Denny Island',
    'Sorrento',
    'Skookumchuck',
    'Tappen',
    'Kootenay Bay',
    'Summit Lake',
    'Lund',
    'Sooke',
    'Newgate',
    'Heriot Bay',
    'Watch Lake',
    'Comox',
    'Telegraph Cove',
    'Tetsa River',
    'Queen Charlotte City',
    'Riske Creek',
    'Gray Creek',
    'Oyama',
    'Savona',
    'Peachland',
    'Fort Nelson',
    'Quathiaski Cove',
    'Tsawwassen',
    'Gold Bridge',
    'Williams Lake',
    'Terrace',
    'Clinton',
    'Witset',
    'Ainsworth Hot Springs',
    'Barriere',
    'Field'
];

export default cities;
