const constants = {
  'ADD_CAMPGROUND': 'ADD_CAMPGROUND',
  'REMOVE_CAMPGROUND': 'REMOVE_CAMPGROUND',
  'MAKE_RESERVATION': 'MAKE_RESERVATION',
  'CANCEL_RESERVATION': 'CANCEL_RESERVATION',
  'FETCH_RESERVATIONS': 'FETCH_RESERVATIONS',
  'ADD_ERROR': 'ADD_ERROR',
  'CLEAR_ERROR': 'CLEAR_ERROR',
  'FETCH_CAMPGROUNDS': 'FETCH_CAMPGROUNDS',
  'FETCH_CAMPGROUND_DETAILS': 'FETCH_CAMPGROUND_DETAILS',
  'FETCH_ARTICLES': 'FETCH_ARTICLES',
  'FETCH_ARTICLE_DETAILS': 'FETCH_ARTICLE_DETAILS',
  'CANCEL_FETCHING': 'CANCEL_FETCHING',
  'CHANGE_SUGGESTIONS': 'CHANGE_SUGGESTIONS',
  'CLEAR_SUGGESTIONS': 'CLEAR_SUGGESTIONS',
  'SUBSCRIBE': 'SUBSCRIBE',
  'SUBMIT_CONTACT_FORM': 'SUBMIT_CONTACT_FORM',
  'FETCH_ACCOUNT': 'FETCH_ACCOUNT'
}

export default constants;
